CREATE DATABASE QLGV
GO

USE QLGV
GO


-- Bảng KHOA
CREATE TABLE KHOA 
(
    MAKHOA VARCHAR(4) PRIMARY KEY,
    TENKHOA VARCHAR(40),
    NGTLAP SMALLDATETIME,
    TRGKHOA CHAR(4)
)

-- Bảng MONHOC
CREATE TABLE MONHOC
(
    MAMH VARCHAR(10) PRIMARY KEY,
    TENMH VARCHAR(40),
    TCLT TINYINT,
    TCTH TINYINT,
    MAKHOA VARCHAR(4) REFERENCES KHOA(MAKHOA) -- Khóa ngoại
)

-- Bảng DIEUKIEN
CREATE TABLE DIEUKIEN
(
    MAMH VARCHAR(10),
    MAMH_TRUOC VARCHAR(10),
    PRIMARY KEY (MAMH, MAMH_TRUOC),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH), -- Khóa ngoại
    FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH) -- Khóa ngoại
)

-- Bảng GIAOVIEN
CREATE TABLE GIAOVIEN
(
    MAGV CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40),
    HOCVI VARCHAR(10),
    HOCHAM VARCHAR(10),
    GIOITINH VARCHAR(3),
    NGSINH SMALLDATETIME,
    NGVL SMALLDATETIME,
    HESO NUMERIC(4,2),
    MUCLUONG MONEY,
    MAKHOA VARCHAR(4) REFERENCES KHOA(MAKHOA) -- Khóa ngoại
)

-- Bảng HOCVIEN
CREATE TABLE HOCVIEN
(
    MAHV CHAR(5) PRIMARY KEY,
    HO VARCHAR(40),
    TEN VARCHAR(10),
    NGSINH SMALLDATETIME,
    GIOITINH VARCHAR(3),
    NOISINH VARCHAR(40),
    MALOP CHAR(3) REFERENCES LOP(MALOP) -- Khóa ngoại
)

-- Bảng LOP
CREATE TABLE LOP
(
    MALOP CHAR(3) PRIMARY KEY,
    TENLOP VARCHAR(40),
    TRGLOP CHAR(5) REFERENCES HOCVIEN(MAHV), -- Khóa ngoại
    SISO TINYINT,
    MAGVCN CHAR(4) REFERENCES GIAOVIEN(MAGV) -- Khóa ngoại
)

-- Bảng GIANGDAY
CREATE TABLE GIANGDAY
(
    MALOP CHAR(3),
    MAMH VARCHAR(10),
    MAGV CHAR(4),
    HOCKY TINYINT,
    NAM SMALLINT,
    TUNGAY SMALLDATETIME,
    DENNGAY SMALLDATETIME,
    PRIMARY KEY (MALOP, MAMH),
    FOREIGN KEY (MALOP) REFERENCES LOP(MALOP), -- Khóa ngoại
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH), -- Khóa ngoại
    FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV) -- Khóa ngoại
)

-- Bảng KETQUATHI
CREATE TABLE KETQUATHI
(
    MAHV CHAR(5),
    MAMH VARCHAR(10),
    LANTHI TINYINT,
    NGTHI SMALLDATETIME,
    DIEM NUMERIC(4,2),
    KQUA VARCHAR(10),
    PRIMARY KEY (MAHV, MAMH, LANTHI),
    FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV), -- Khóa ngoại
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH) -- Khóa ngoại
)


-- Thêm vào 3 thuộc tính GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN
ALTER TABLE HOCVIEN 
ADD GHICHU VARCHAR(50), DIEMTB NUMERIC(4,2), XEPLOAI VARCHAR(10)

--3. Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”
ALTER TABLE HOCVIEN 
ADD CONSTRAINT CHK_GTHV CHECK (GIOITINH IN ('Nam', 'Nu'))
ALTER TABLE GIAOVIEN 
ADD CONSTRAINT CHK_GTGV CHECK (GIOITINH IN ('Nam', 'Nu'))

--4. Điểm số của một lần thi có giá trị từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22)
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_DIEM CHECK 
(
    DIEM BETWEEN 0 AND 10
    AND DIEM = ROUND(DIEM, 2)
)

--5. Kết quả thi là “Dat” nếu điểm từ 5 đến 10 và “Khong dat” nếu điểm nhỏ hơn 5
ALTER TABLE KETQUATHI
ADD CONSTRAINT CHK_KQUA CHECK(KQUA = IIF(DIEM BETWEEN 5 AND 10, 'Dat', 'Khong dat'))

--6. Học viên thi một môn tối đa 3 lần
ALTER TABLE KETQUATHI 
ADD CONSTRAINT CHK_LANTHI CHECK (LANTHI <= 3)

--7. Học kỳ chỉ có giá trị từ 1 đến 3
ALTER TABLE GIANGDAY 
ADD CONSTRAINT CHK_HOCKY CHECK (HOCKY BETWEEN 1 AND 3)

--8. Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”
ALTER TABLE GIAOVIEN 
ADD CONSTRAINT CHK_HOCVI CHECK (HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))

